flaskshop/dashboard/models.py
from flask import url_for, request

from flaskshop.database import Column, Model, db
from flaskshop.constant import SettingValueType


class DashboardMenu(Model):
    __tablename__ = "management_dashboard"
    title = Column(db.String(255), nullable=False)
    order = Column(db.Integer(), default=0)
    endpoint = Column(db.String(255))
    icon_cls = Column(db.String(255))
    parent_id = Column(db.Integer(), default=0)

    def __str__(self):
        return self.title

    @property
    def children(self):
        return DashboardMenu.query.filter(DashboardMenu.parent_id == self.id).all()

    @classmethod
    def first_level_items(cls):
        return cls.query.filter(cls.parent_id == 0).order_by("order").all()

    def is_active(self):
        if self.endpoint and self.endpoint in request.path:
            return True
        if any((child.is_active() for child in self.children)):
            return True
        return False

    def get_url(self):
        if self.children:
            return "#"
        if self.endpoint:
            return url_for("dashboard." + self.endpoint)


class Setting(Model):
    __tablename__ = "management_setting"
    id = None
    key = Column(db.String(255), primary_key=True)
    value = Column(db.PickleType, nullable=False)
    name = Column(db.String(255), nullable=False)
    description = Column(db.Text, nullable=False)
    value_type = Column(db.Enum(SettingValueType), nullable=False)
    extra = Column(db.PickleType)

    @classmethod
    def get_settings(cls):
        settings = {}
        for s in cls.query.all():
            settings[s.key] = s.value
        return settings

    @classmethod
    def update(cls, settings):
        """Updates the cache and stores the changes in the
        database.
        :param settings: A dictionary with setting items.
        """
        # update the database
        for key, value in settings.items():
            setting = cls.query.filter(Setting.key == key.lower()).first()

            setting.value = value

            db.session.add(setting)
        db.session.commit()

    def __repr__(self):
        return f"<{self.__class__.__name__} {self.key}>"

flaskshop/dashboard/__init__.py
from . import views

flaskshop/dashboard/views/__init__.py
from . import bp

flaskshop/dashboard/views/bp.py
from datetime import datetime
from flask import Blueprint, render_template
from flask_login import login_required
from pluggy import HookimplMarker
from sqlalchemy import func

from flaskshop.extensions import db
from flaskshop.dashboard.models import DashboardMenu
from flaskshop.order.models import Order, OrderLine, OrderEvent
from flaskshop.product.models import Product
from flaskshop.account.models import User
from flaskshop.account.utils import permission_required
from flaskshop.settings import Config
from flaskshop.constant import Permission, OrderStatusKinds, OrderEvents

from .user import users, user, user_edit, address_edit
from .site import (
    shipping_methods,
    shipping_methods_manage,
    site_menus,
    site_menus_manage,
    dashboard_menus,
    dashboard_menus_manage,
    site_pages,
    site_pages_manage,
    site_setting,
    plugin_list,
    plugin_enable,
    plugin_disable,
    config_index,
)
from .product import (
    attributes,
    attributes_manage,
    collections,
    collections_manage,
    categories,
    categories_manage,
    product_types,
    product_types_manage,
    products,
    product_detail,
    product_edit,
    product_create_step1,
    product_create_step2,
    variant_manage,
)
from .order import orders, order_detail, send_order, draft_order
from .discount import vouchers, vouchers_manage, sales, sales_manage

impl = HookimplMarker("flaskshop")


def index():
    def get_today_num(model):
        target = db.cast(datetime.now(), db.DATE)
        which = db.cast(model.created_at, db.DATE)
        return model.query.filter(which == target).count()

    def get_order_status(status):
        return {
            "count": Order.query.filter_by(status=status).count(),
            "kind": status,
        }

    onsale_products_count = Product.query.filter_by(on_sale=True).count()

    hot_product_ids = (
        db.session.query(OrderLine.product_id, func.count(OrderLine.product_id))
        .group_by(OrderLine.product_id)
        .order_by(func.count(OrderLine.product_id).desc())
        .all()
    )
    top5_products = []
    for product_id, order_count in hot_product_ids[:5]:
        p = Product.get_by_id(product_id)
        p.order_count = order_count
        top5_products.append(p)

    activity = OrderEvent.query.order_by(OrderEvent.id.desc()).limit(10)

    context = {
        "orders_total": Order.query.count(),
        "orders_today": get_today_num(Order),
        "users_total": User.query.count(),
        "users_today": get_today_num(User),
        "order_unfulfill": get_order_status(OrderStatusKinds.unfulfilled.value),
        "order_fulfill": get_order_status(OrderStatusKinds.fulfilled.value),
        "onsale_products_count": onsale_products_count,
        "top_products": top5_products,
        "activity": activity,
        "order_events": OrderEvents,
    }
    return render_template("index.html", **context)


@impl
def flaskshop_load_blueprints(app):
    bp = Blueprint(
        "dashboard", __name__, template_folder=Config.DASHBOARD_TEMPLATE_FOLDER
    )

    @bp.context_processor
    def inject_param():
        menus = DashboardMenu.first_level_items()
        return {"menus": menus}

    @bp.before_request
    @permission_required(Permission.EDITOR)
    @login_required
    def before_request():
        """The whole blueprint need to login first"""
        pass

    bp.add_url_rule("/", view_func=index)
    bp.add_url_rule("/site_menus", view_func=site_menus)
    bp.add_url_rule(
        "/site_menus/create", view_func=site_menus_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/site_menus/<id>/edit", view_func=site_menus_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule("/dashboard_menus", view_func=dashboard_menus)
    bp.add_url_rule(
        "/dashboard_menus/create",
        view_func=dashboard_menus_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/dashboard_menus/<id>/edit",
        view_func=dashboard_menus_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule("/site_pages", view_func=site_pages)
    bp.add_url_rule(
        "/site_pages/create", view_func=site_pages_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/site_pages/<id>/edit", view_func=site_pages_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule("/site_setting", view_func=site_setting, methods=["GET", "POST"])
    bp.add_url_rule("/plugin", view_func=plugin_list)
    bp.add_url_rule("/plugin/<id>/enable", view_func=plugin_enable, methods=["POST"])
    bp.add_url_rule("/plugin/<id>/disable", view_func=plugin_disable, methods=["POST"])
    bp.add_url_rule("/config", view_func=config_index)
    bp.add_url_rule("/users", view_func=users)
    bp.add_url_rule("/users/<user_id>", view_func=user)
    bp.add_url_rule(
        "/users/<user_id>/edit", view_func=user_edit, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/users/address/<id>/edit", view_func=address_edit, methods=["GET", "POST"]
    )
    bp.add_url_rule("/attributes", view_func=attributes)
    bp.add_url_rule(
        "/attributes/create", view_func=attributes_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/attributes/<id>/edit", view_func=attributes_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule("/collections", view_func=collections)
    bp.add_url_rule(
        "/collections/create", view_func=collections_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/collections/<id>/edit", view_func=collections_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule("/categories", view_func=categories)
    bp.add_url_rule(
        "/categories/create", view_func=categories_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/categories/<id>/edit", view_func=categories_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule("/product_types", view_func=product_types)
    bp.add_url_rule(
        "/product_types/create", view_func=product_types_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/product_types/<id>/edit",
        view_func=product_types_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule("/shipping_methods", view_func=shipping_methods)
    bp.add_url_rule(
        "/shipping_methods/create",
        view_func=shipping_methods_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/shipping_methods/<id>/edit",
        view_func=shipping_methods_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule("/products", view_func=products)
    bp.add_url_rule("/products/<id>", view_func=product_detail)
    bp.add_url_rule(
        "/products/create/step1",
        view_func=product_create_step1,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/products/create/step2",
        view_func=product_create_step2,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/products/<id>/edit", view_func=product_edit, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/products/variant/create", view_func=variant_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/products/variant/<id>/edit", view_func=variant_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule("/orders", view_func=orders)
    bp.add_url_rule("/orders/<id>", view_func=order_detail)
    bp.add_url_rule("/orders/<id>/send", view_func=send_order)
    bp.add_url_rule("/orders/<id>/draft", view_func=draft_order)
    bp.add_url_rule("/vouchers", view_func=vouchers)
    bp.add_url_rule(
        "/vouchers/create", view_func=vouchers_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/vouchers/<id>/edit", view_func=vouchers_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule("/sales", view_func=sales)
    bp.add_url_rule("/sales/create", view_func=sales_manage, methods=["GET", "POST"])
    bp.add_url_rule("/sales/<id>/edit", view_func=sales_manage, methods=["GET", "POST"])
    app.register_blueprint(bp, url_prefix="/dashboard")

flaskshop/dashboard/views/discount.py
from datetime import datetime

from flask import request, render_template, redirect, url_for

from flaskshop.discount.models import Voucher, Sale, SaleCategory, SaleProduct
from flaskshop.product.models import Product, Category
from flaskshop.dashboard.forms import VoucherForm, SaleForm
from flaskshop.constant import VoucherTypeKinds, DiscountValueTypeKinds


def vouchers():
    page = request.args.get("page", type=int, default=1)
    pagination = Voucher.query.paginate(page, 10)
    props = {
        "id": "ID",
        "title": "Title",
        "type_human": "Type",
        "usage_limit": "Usage Limit",
        "used": "Used",
        "discount_value_type_human": "Discount Type",
        "discount_value": "Discount Value",
    }
    context = {
        "title": "Voucher",
        "items": pagination.items,
        "props": props,
        "pagination": pagination,
        "identity": "vouchers",
    }
    return render_template("list.html", **context)


def vouchers_manage(id=None):
    if id:
        voucher = Voucher.get_by_id(id)
        form = VoucherForm(obj=voucher)
    else:
        form = VoucherForm()
    if form.validate_on_submit():
        if not id:
            voucher = Voucher()
        start_date, end_date = form.validity_period.data.split("-")
        voucher.start_date = datetime.strptime(start_date.strip(), "%m/%d/%Y")
        voucher.end_date = datetime.strptime(end_date.strip(), "%m/%d/%Y")
        del form.validity_period
        form.populate_obj(voucher)
        voucher.save()
        return redirect(url_for("dashboard.vouchers"))
    products = Product.query.all()
    categories = Category.query.all()
    voucher_types = [dict(id=kind.value, title=kind.name) for kind in VoucherTypeKinds]
    discount_types = [
        dict(id=kind.value, title=kind.name) for kind in DiscountValueTypeKinds
    ]
    context = {
        "form": form,
        "products": products,
        "categories": categories,
        "voucher_types": voucher_types,
        "discount_types": discount_types,
    }
    return render_template("discount/voucher.html", **context)


def sales():
    page = request.args.get("page", type=int, default=1)
    pagination = Sale.query.paginate(page, 10)
    props = {
        "id": "ID",
        "title": "Title",
        "discount_value_type_label": "Discount Type",
        "discount_value": "Discount Value",
    }
    context = {
        "title": "Sale",
        "items": pagination.items,
        "props": props,
        "pagination": pagination,
        "identity": "sales",
    }
    return render_template("list.html", **context)


def sales_manage(id=None):
    if id:
        sale = Sale.get_by_id(id)
        form = SaleForm(obj=sale)
    else:
        form = SaleForm()
    if form.validate_on_submit():
        if not id:
            sale = Sale()
        sale.update_products(form.products.data)
        sale.update_categories(form.categories.data)
        del form.products
        del form.categories
        form.populate_obj(sale)
        sale.save()
        return redirect(url_for("dashboard.sales"))
    products = Product.query.all()
    categories = Category.query.all()
    discount_types = [
        dict(id=kind.value, title=kind.name) for kind in DiscountValueTypeKinds
    ]
    context = {
        "form": form,
        "products": products,
        "categories": categories,
        "discount_types": discount_types,
    }
    return render_template("discount/sale.html", **context)

flaskshop/dashboard/views/order.py
from datetime import datetime

from flask import request, render_template

from flaskshop.order.models import Order
from flaskshop.constant import OrderStatusKinds


def orders():
    page = request.args.get("page", type=int, default=1)
    query = Order.query.order_by(Order.id.desc())

    status = request.args.get("status", type=int)
    if status:
        query = query.filter_by(status=status)
    order_no = request.args.get("order_number", type=str)
    if order_no:
        query = query.filter(Order.token.like(f"%{order_no}%"))
    created_at = request.args.get("created_at", type=str)
    if created_at:
        start_date, end_date = created_at.split("-")
        start_date = datetime.strptime(start_date.strip(), "%m/%d/%Y")
        end_date = datetime.strptime(end_date.strip(), "%m/%d/%Y")
        query = query.filter(Order.created_at.between(start_date, end_date))
    pagination = query.paginate(page, 10)
    props = {
        "id": "ID",
        "identity": "Identity",
        "status_human": "Status",
        "total_human": "Total",
        "user": "User",
        "created_at": "Created At",
    }
    context = {
        "items": pagination.items,
        "props": props,
        "pagination": pagination,
        "order_stats_kinds": OrderStatusKinds,
    }
    return render_template("order/list.html", **context)


def order_detail(id):
    order = Order.get_by_id(id)
    return render_template("order/detail.html", order=order)


def send_order(id):
    order = Order.get_by_id(id)
    order.delivered()
    return render_template("order/detail.html", order=order)


def draft_order(id):
    order = Order.get_by_id(id)
    order.draft()
    return render_template("order/detail.html", order=order)

flaskshop/dashboard/views/user.py
from flask import render_template, redirect, url_for, request
from sqlalchemy import or_

from flaskshop.account.models import User, UserAddress
from flaskshop.order.models import Order
from flaskshop.dashboard.forms import UserForm, UserAddressForm


def users():
    page = request.args.get("page", type=int, default=1)
    search_word = request.args.get("keyword")
    query = User.query
    if search_word:
        query = query.filter(
            or_(
                User.username.like("%" + search_word + "%"),
                User.email.like("%" + search_word + "%"),
            )
        )
    pagination = query.paginate(page, 10)
    props = {
        "id": "ID",
        "username": "Username",
        "email": "Email",
        "is_active_human": "Is Active",
    }
    context = {
        "title": "User List",
        "items": pagination.items,
        "props": props,
        "pagination": pagination,
    }
    return render_template("user/list.html", **context)


def user(user_id):
    user = User.get_by_id(user_id)
    addresses = user.addresses
    orders = Order.get_user_orders(user_id)
    context = {"user": user, "addresses": addresses, "orders": orders}
    return render_template("user/detail.html", **context)


def user_edit(user_id):
    user = User.get_by_id(user_id)
    form = UserForm(obj=user)
    if form.validate_on_submit():
        if not form.password.data:
            del form.password
        form.populate_obj(user)
        user.save()
        return redirect(url_for("dashboard.user", user_id=user_id))
    return render_template("user/edit.html", form=form)


def address_edit(id):
    addr = UserAddress.get_by_id(id)
    form = UserAddressForm(obj=addr)
    if form.validate_on_submit():
        form.populate_obj(addr)
        addr.save()
        return redirect(url_for("dashboard.user", user_id=addr.user_id))
    return render_template("user/edit_addr.html", form=form)

flaskshop/order/__init__.py
from . import views

flaskshop/order/payment/__init__.py
from . import zhifubao

flaskshop/templates/dashboard/order/detail.html
{% import 'dashboard/_vendor.html' as vendor %}
{% extends 'dashboard/layout.html' %}
{% block body %}
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="invoice p-3 mb-3">
                    <!-- title row -->
                    <div class="row">
                        <div class="col-12">
                            <h4>
                                <i class="fa fa-globe"></i> {{order.token}}
                                <small class="float-right">Created At: {{order.created_at}}</small>
                            </h4>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- info row -->
                    <div class="row invoice-info">
                        <div class="col-sm-4 invoice-col">
                            <b>Status:</b> {{order.status_human}}<br>
                            <b>Payment Status:</b> {{order.payment.status_human}}<br>
                            <b>Payment Due:</b> {{order.payment.paid_at}}<br>
                            <b>Account:</b> {{order.user}}
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                            <strong>Shipping Address</strong>
                            <address>
                                {{order.shipping_address | safe}}
                            </address>
                        </div>
                        <div class="col-sm-4 invoice-col">
                            <strong>Shipping Method</strong>
                            <address>
                                {{order.shipping_method_name}} (${{order.shipping_price_net}})
                            </address>
                        </div>
                    </div>
                    <!-- /.row -->

                    <!-- Table row -->
                    <div class="row">
                        <div class="col-12 table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Qty</th>
                                        <th>Product</th>
                                        <th>SKU</th>
                                        <th>Unit Price</th>
                                        <th>Subtotal</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in order.lines %}
                                    <tr>
                                        <td>{{item.quantity}}</td>
                                        <td>
                                            <a href="{{url_for('dashboard.product_detail', id=item.product_id)}}"
                                                target="_blank">
                                                {{item.product_name}}
                                            </a>
                                        </td>
                                        <td>{{item.product_sku}}</td>
                                        <td>${{item.unit_price_net}}</td>
                                        <td>${{item.quantity * item.unit_price_net}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->

                    <div class="row">
                        <!-- accepted payments column -->
                        <div class="col-6">
                            <p class="lead">Payment Method: {{order.payment.payment_method}}</p>
                            <p class="lead">Order Note:</p>
                            <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
                                {{order.note}}
                            </p>
                        </div>
                        <!-- /.col -->
                        <div class="col-6">
                            <div class="table-responsive">
                                <table class="table">
                                    <tr>
                                        <th style="width:50%">Subtotal:</th>
                                        <td>${{order.total_net}}</td>
                                    </tr>
                                    <tr>
                                        <th>Shipping:</th>
                                        <td>${{order.shipping_price_net}}</td>
                                    </tr>

                                    <tr>
                                        <th>Discount:</th>
                                        <td>-${{ order.discount_amount  }}({{ order.discount_name }})</td>
                                    </tr>

                                    <tr>
                                        <th>Total:</th>
                                        <td>${{order.total}}</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->

                    <div class="row no-print">
                        <div class="col-12">
                            {% if order.status_human == "fulfilled" %}
                            <a class="btn btn-success float-right"
                                href="{{url_for('dashboard.send_order', id=order.id)}}">
                                <i class="fa fa-credit-card"></i> Send Order
                            </a>
                            {% elif order.status_human == "unfulfilled" %}
                            <a class="btn btn-danger float-right"
                                href="{{url_for('dashboard.draft_order', id=order.id)}}">
                                <i class="fa fa-ban"></i> Draft Order
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
{% endblock %}

flaskshop/templates/dashboard/order/list.html
{% import 'dashboard/_vendor.html' as vendor %}
{% extends 'dashboard/layout.html' %}
{% block body %}
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title" style="line-height: 30px;">Order List</h3>
                        <div class="card-tools">
                            <form>
                            <div class="row">
                                <div class="form-group col-2">
                                <select class="form-control" name="status">
                                    <option value="" disabled selected hidden>Status</option>
                                    {% for stat in order_stats_kinds%}
                                    <option value="{{stat.value}}">{{stat.name}}</option>
                                    {% endfor %}
                                </select>
                                </div>
                                <div class="form-group col-3">
                                    <input type="text" name="order_number" class="float-right form-control"
                                        placeholder="Order No.">
                                </div>
                                <div class="form-group col-5">
                                    <input type="text" name="created_at" class="float-right form-control" 
                                        placeholder="Created At" id="reservation">
                                </div>
                                <div class="form-group col-2">
                                    <button type="submit" class="btn btn-default">Query</button>
                                </div>
                            </div>
                            </form>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover">
                            <tr>
                                {% for th in props.values() %}
                                <th>{{th}}</th>
                                {% endfor %}
                                <th>Operation</th>
                            </tr>
                            {% for item in items %}
                            <tr>
                                {% for prop in props.keys() %}
                                <td>{{ item | attr(prop) }}</td>
                                {% endfor %}
                                <td>
                                    <a href="{{url_for('dashboard.order_detail', id=item.id)}}"
                                        class="btn btn-info btn-sm">View</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>
                    <!-- /.card-body -->
                    {% if pagination %}
                    <div class="card-footer clearfix">
                        {{vendor.render_pagination(pagination, size='sm', align='right')}}
                    </div>
                    {% endif %}
                </div>
                <!-- /.card -->
            </div>
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</section>

{% endblock %}

{% block tail_js %}
<script src="{{ url_for('static', filename='build/dashboard/daterangepicker.js') }}"></script>
{% endblock %}