flaskshop/order/models.py
from flask import url_for
from flask_login import current_user
from uuid import uuid4
from sqlalchemy.dialects.mysql import TINYINT

from flaskshop.database import Column, Model, db
from flaskshop.account.models import User, UserAddress
from flaskshop.product.models import ProductVariant
from flaskshop.constant import (
    OrderStatusKinds,
    PaymentStatusKinds,
    OrderEvents,
    ShipStatusKinds,
)
from flaskshop.checkout.models import ShippingMethod
from flaskshop.discount.models import Voucher


class Order(Model):
    __tablename__ = "order_order"
    token = Column(db.String(100), unique=True)
    shipping_address = Column(db.String(255))
    user_id = Column(db.Integer())
    total_net = Column(db.DECIMAL(10, 2))
    discount_amount = Column(db.DECIMAL(10, 2), default=0)
    discount_name = Column(db.String(100))
    voucher_id = Column(db.Integer())
    shipping_price_net = Column(db.DECIMAL(10, 2))
    status = Column(TINYINT())
    shipping_method_name = Column(db.String(100))
    shipping_method_id = Column(db.Integer())
    ship_status = Column(TINYINT())

    def __str__(self):
        return f"#{self.identity}"

    @classmethod
    def create_whole_order(cls, cart, note=None):
        # Step1, certify stock, voucher
        to_update_variants = []
        to_update_orderlines = []
        total_net = 0
        for line in cart.lines:
            variant = ProductVariant.get_by_id(line.variant.id)
            result, msg = variant.check_enough_stock(line.quantity)
            if result is False:
                return result, msg
            variant.quantity_allocated += line.quantity
            to_update_variants.append(variant)
            orderline = OrderLine(
                variant_id=variant.id,
                quantity=line.quantity,
                product_name=variant.display_product(),
                product_sku=variant.sku,
                product_id=variant.sku.split("-")[0],
                unit_price_net=variant.price,
                is_shipping_required=variant.is_shipping_required,
            )
            to_update_orderlines.append(orderline)
            total_net += orderline.get_total()

        voucher = None
        if cart.voucher_code:
            voucher = Voucher.get_by_code(cart.voucher_code)
            try:
                voucher.check_available(cart)
            except Exception as e:
                return False, str(e)

        # Step2, create Order obj
        try:
            shipping_method_id = None
            shipping_method_title = None
            shipping_method_price = 0
            shipping_address = None

            if cart.shipping_method_id:
                shipping_method = ShippingMethod.get_by_id(cart.shipping_method_id)
                shipping_method_id = shipping_method.id
                shipping_method_title = shipping_method.title
                shipping_method_price = shipping_method.price
                shipping_address = UserAddress.get_by_id(
                    cart.shipping_address_id
                ).full_address

            order = cls.create(
                user_id=current_user.id,
                token=str(uuid4()),
                shipping_method_id=shipping_method_id,
                shipping_method_name=shipping_method_title,
                shipping_price_net=shipping_method_price,
                shipping_address=shipping_address,
                status=OrderStatusKinds.unfulfilled.value,
                total_net=total_net,
            )
        except Exception as e:
            return False, str(e)

        # Step3, process others
        if note:
            order_note = OrderNote(
                order_id=order.id, user_id=current_user.id, content=note
            )
            db.session.add(order_note)
        if voucher:
            order.voucher_id = voucher.id
            order.discount_amount = voucher.get_vouchered_price(cart)
            order.discount_name = voucher.title
            voucher.used += 1
            db.session.add(order)
            db.session.add(voucher)
        for variant in to_update_variants:
            db.session.add(variant)
        for orderline in to_update_orderlines:
            orderline.order_id = order.id
            db.session.add(orderline)
        for line in cart.lines:
            db.session.delete(line)
        db.session.delete(cart)

        db.session.commit()
        return order, "success"

    def get_absolute_url(self):
        return url_for("order.show", token=self.token)

    @property
    def identity(self):
        return self.token.split("-")[-1]

    @property
    def total(self):
        return self.total_net + self.shipping_price_net - self.discount_amount

    @property
    def status_human(self):
        return OrderStatusKinds(int(self.status)).name

    @property
    def total_human(self):
        return "$" + str(self.total)

    @classmethod
    def get_current_user_orders(cls):
        if current_user.is_authenticated:
            orders = (
                cls.query.filter_by(user_id=current_user.id)
                .order_by(Order.id.desc())
                .all()
            )
        else:
            orders = []
        return orders

    @classmethod
    def get_user_orders(cls, user_id):
        return cls.query.filter_by(user_id=user_id).all()

    @property
    def is_shipping_required(self):
        return any(line.is_shipping_required for line in self.lines)

    @property
    def is_self_order(self):
        return self.user_id == current_user.id

    @property
    def lines(self):
        return OrderLine.query.filter(OrderLine.order_id == self.id).all()

    @property
    def notes(self):
        return OrderNote.query.filter(OrderNote.order_id == self.id).all()

    @property
    def user(self):
        return User.get_by_id(self.user_id)

    @property
    def payment(self):
        return OrderPayment.query.filter_by(order_id=self.id).first()

    def pay_success(self, payment):
        self.status = OrderStatusKinds.fulfilled.value
        # to resolve another instance with key is already present in this session
        local_obj = db.session.merge(self)
        db.session.add(local_obj)

        for line in self.lines:
            variant = line.variant
            variant.quantity_allocated -= line.quantity
            variant.quantity -= line.quantity
            db.session.add(variant)

        db.session.commit()

        OrderEvent.create(
            order_id=self.id,
            user_id=self.user_id,
            type_=OrderEvents.payment_captured.value,
        )

    def cancel(self):
        self.status = OrderStatusKinds.canceled.value
        db.session.add(self)

        for line in self.lines:
            variant = line.variant
            variant.quantity_allocated -= line.quantity
            db.session.add(variant)

        db.session.commit()

        OrderEvent.create(
            order_id=self.id,
            user_id=self.user_id,
            type_=OrderEvents.order_canceled.value,
        )

    def complete(self):
        self.update(status=OrderStatusKinds.completed.value)
        OrderEvent.create(
            order_id=self.id,
            user_id=self.user_id,
            type_=OrderEvents.order_completed.value,
        )

    def draft(self):
        self.update(status=OrderStatusKinds.draft.value)
        OrderEvent.create(
            order_id=self.id,
            user_id=self.user_id,
            type_=OrderEvents.draft_created.value,
        )

    def delivered(self):
        self.update(
            status=OrderStatusKinds.shipped.value,
            ship_status=ShipStatusKinds.delivered.value,
        )
        OrderEvent.create(
            order_id=self.id,
            user_id=self.user_id,
            type_=OrderEvents.order_delivered.value,
        )


class OrderLine(Model):
    __tablename__ = "order_line"
    product_name = Column(db.String(255))
    product_sku = Column(db.String(100))
    quantity = Column(db.Integer())
    unit_price_net = Column(db.DECIMAL(10, 2))
    is_shipping_required = Column(db.Boolean(), default=True)
    order_id = Column(db.Integer())
    variant_id = Column(db.Integer())
    product_id = Column(db.Integer())

    @property
    def variant(self):
        return ProductVariant.get_by_id(self.variant_id)

    def get_total(self):
        return self.unit_price_net * self.quantity


class OrderNote(Model):
    __tablename__ = "order_note"
    order_id = Column(db.Integer())
    user_id = Column(db.Integer())
    content = Column(db.Text())
    is_public = Column(db.Boolean(), default=True)


class OrderPayment(Model):
    __tablename__ = "order_payment"
    order_id = Column(db.Integer())
    status = Column(TINYINT)
    total = Column(db.DECIMAL(10, 2))
    delivery = Column(db.DECIMAL(10, 2))
    description = Column(db.Text())
    customer_ip_address = Column(db.String(100))
    token = Column(db.String(100))
    payment_method = Column(db.String(255))
    payment_no = Column(db.String(255), unique=True)
    paid_at = Column(db.DateTime())

    def pay_success(self, paid_at):
        self.paid_at = paid_at
        self.status = PaymentStatusKinds.confirmed.value
        self.save(commit=False)
        order = Order.get_by_id(self.order_id)
        order.pay_success(payment=self)

    @property
    def status_human(self):
        return PaymentStatusKinds(int(self.status)).name


class OrderEvent(Model):
    __tablename__ = "order_event"
    order_id = Column(db.Integer())
    user_id = Column(db.Integer())
    type_ = Column("type", TINYINT())

flaskshop/dashboard/views/order.py
from datetime import datetime

from flask import request, render_template

from flaskshop.order.models import Order
from flaskshop.constant import OrderStatusKinds


def orders():
    page = request.args.get("page", type=int, default=1)
    query = Order.query.order_by(Order.id.desc())

    status = request.args.get("status", type=int)
    if status:
        query = query.filter_by(status=status)
    order_no = request.args.get("order_number", type=str)
    if order_no:
        query = query.filter(Order.token.like(f"%{order_no}%"))
    created_at = request.args.get("created_at", type=str)
    if created_at:
        start_date, end_date = created_at.split("-")
        start_date = datetime.strptime(start_date.strip(), "%m/%d/%Y")
        end_date = datetime.strptime(end_date.strip(), "%m/%d/%Y")
        query = query.filter(Order.created_at.between(start_date, end_date))
    pagination = query.paginate(page, 10)
    props = {
        "id": "ID",
        "identity": "Identity",
        "status_human": "Status",
        "total_human": "Total",
        "user": "User",
        "created_at": "Created At",
    }
    context = {
        "items": pagination.items,
        "props": props,
        "pagination": pagination,
        "order_stats_kinds": OrderStatusKinds,
    }
    return render_template("order/list.html", **context)


def order_detail(id):
    order = Order.get_by_id(id)
    return render_template("order/detail.html", order=order)


def send_order(id):
    order = Order.get_by_id(id)
    order.delivered()
    return render_template("order/detail.html", order=order)


def draft_order(id):
    order = Order.get_by_id(id)
    order.draft()
    return render_template("order/detail.html", order=order)

flaskshop/order/__init__.py
from . import views

flaskshop/order/payment/__init__.py
from . import zhifubao

flaskshop/order/views.py
import time
from datetime import datetime

from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    current_app,
    url_for,
    abort,
)
from flask_login import login_required, current_user
from pluggy import HookimplMarker

from .models import Order, OrderPayment
from .payment import zhifubao
from flaskshop.extensions import csrf_protect
from flaskshop.constant import ShipStatusKinds, PaymentStatusKinds, OrderStatusKinds

impl = HookimplMarker("flaskshop")


@login_required
def index():
    return redirect(url_for("account.index"))


@login_required
def show(token):
    order = Order.query.filter_by(token=token).first()
    if not order.is_self_order:
        abort(403, "This is not your order!")
    return render_template("orders/details.html", order=order)


def create_payment(token, payment_method):
    order = Order.query.filter_by(token=token).first()
    if order.status != OrderStatusKinds.unfulfilled.value:
        abort(403, "This Order Can Not Pay")
    payment_no = str(int(time.time())) + str(current_user.id)
    customer_ip_address = request.headers.get("X-Forwarded-For", request.remote_addr)
    payment = OrderPayment.query.filter_by(order_id=order.id).first()
    if payment:
        payment.update(
            payment_method=payment_method,
            payment_no=payment_no,
            customer_ip_address=customer_ip_address,
        )
    else:
        payment = OrderPayment.create(
            order_id=order.id,
            payment_method=payment_method,
            payment_no=payment_no,
            status=PaymentStatusKinds.waiting.value,
            total=order.total,
            customer_ip_address=customer_ip_address,
        )
    if payment_method == "alipay":
        order_string = zhifubao.send_order(order.token, payment_no, order.total)
        payment.order_string = order_string
    return payment


@login_required
def ali_pay(token):
    payment = create_payment(token, "alipay")
    return redirect(current_app.config["PURCHASE_URI"] + payment.order_string)


@csrf_protect.exempt
def ali_notify():
    data = request.form.to_dict()
    signature = data.pop("sign")
    success = zhifubao.verify_order(data, signature)
    if success:
        order_payment = OrderPayment.query.filter_by(
            payment_no=data["out_trade_no"]
        ).first()
        order_payment.pay_success(paid_at=data["gmt_payment"])
    return "", 200


# for test pay flow
@login_required
def test_pay(token):
    payment = create_payment(token, "testpay")
    payment.pay_success(paid_at=datetime.now())
    return redirect(url_for("order.payment_success"))


@login_required
def payment_success():
    return render_template("orders/checkout_success.html")


@login_required
def cancel_order(token):
    order = Order.query.filter_by(token=token).first()
    if not order.is_self_order:
        abort(403, "This is not your order!")
    order.cancel()
    return render_template("orders/details.html", order=order)


@login_required
def receive(token):
    order = Order.query.filter_by(token=token).first()
    order.update(
        status=OrderStatusKinds.completed.value,
        ship_status=ShipStatusKinds.received.value,
    )
    return render_template("orders/details.html", order=order)


@impl
def flaskshop_load_blueprints(app):
    bp = Blueprint("order", __name__)
    bp.add_url_rule("/", view_func=index)
    bp.add_url_rule("/<string:token>", view_func=show)
    bp.add_url_rule("/pay/<string:token>/alipay", view_func=ali_pay)
    bp.add_url_rule("/alipay/notify", view_func=ali_notify, methods=["POST"])
    bp.add_url_rule("/pay/<string:token>/testpay", view_func=test_pay)
    bp.add_url_rule("/payment_success", view_func=payment_success)
    bp.add_url_rule("/cancel/<string:token>", view_func=cancel_order)
    bp.add_url_rule("/receive/<string:token>", view_func=receive)
    app.register_blueprint(bp, url_prefix="/orders")

flaskshop/templates/orders/_ordered_items_table.html
{% import '_macros.html' as macros %}

<div class="table__header order-details__table-header d-none d-sm-block">
    <div class="row">
        <div class="col-md-8">
            <small>
                Product
            </small>
        </div>
        <div class="col-md-2 text-right">
            <small>
                Quantity
            </small>
        </div>
        <div class="col-md-2 text-right">
            <small>
                Price
            </small>
        </div>
    </div>
</div>

{% for line in order.lines %}
<div class="table__row order-details__product{% if loop.last %} order-details__last-row{% endif %}">
    <div class="row">
        <div class="col-md-8">
            <a class="link--clean" href="{% if line.variant %}{{ line.variant.get_absolute_url() }}{% endif %}">
                <img class="float-left lazyload lazypreload" src="{{ line.variant.product.first_img }}" width="60">
                <span class="order-details__product__description">{{ line.product_name }}</span>
            </a>
        </div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-6 col-12">
                    <p class="float-right">x {{ line.quantity }}</p>
                </div>
                <div class="col-md-6 col-12">
                    <p class="float-right">
                        ${{ line.get_total() }}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}

<div class="table__row">
    <div class="row">
        <div class="col-8 order-details__table-footer">
            <p>
                Subtotal
            </p>
        </div>
        <div class="col-4">
            <p class="float-right">
                ${{ order.total_net }}
            </p>
            <br>
        </div>
    </div>
</div>

{% if order.is_shipping_required %}
<div class="table__row">
    <div class="row">
        <div class="col-8 order-details__table-footer">
            <p>
                Shipping
                ({{ order.shipping_method_name}})
            </p>
        </div>
        <div class="col-4">
            <p class="float-right">
                ${{ order.shipping_price_net }}
            </p>
        </div>
    </div>
</div>
{% endif %}

{% if order.discount_amount %}
<div class="table__row">
    <div class="row">
        <div class="col-8 order-details__table-footer">
            <p>{{ order.discount_name }}</p>
        </div>
        <div class="col-4">
            <p class="float-right">
                -${{ order.discount_amount  }}
            </p>
        </div>
    </div>
</div>
{% endif %}

<div class="order-details__total">
    <div class="row">
        <div class="col-8 order-details__table-footer">
            <div class="total">
                <h3>Total</h3>
            </div>
        </div>
        <div class="col-4">
            <p class="float-right">
                ${{ order.total  }}
            </p>
        </div>
    </div>
</div>

<div class="order-details__addresses">
    <div class="row">
        <div class="col-6">
            {% if order.is_shipping_required %}
            <h3>
                Shipping address
            </h3>
            {{ order.shipping_address | safe }}
            {% endif %}
        </div>
        {% if order.status_human == "unfulfilled" %}
        <div class="col-6">
            <span class="float-right">Please pay before 00:30, else the order will auto closed</span>
            <a href="{{ url_for('order.ali_pay', token=order.token) }}" class="btn btn-primary float-right">
                Alipay
            </a>
            <a href="{{ url_for('order.test_pay', token=order.token) }}" class="btn secondary float-right">
                Pay for test
            </a>
            <a href="{{ url_for('order.cancel_order', token=order.token) }}" class="btn danger float-right">
                Cancel Order
            </a>
        </div>
        {% elif order.status_human == "shipped" %}
        <div class="col-6">
            <span class="float-right">this order will auto received after 1 day</span>
            <a href="{{ url_for('order.receive', token=order.token) }}" class="btn btn-primary float-right">
                Confirm receipt
            </a>
        </div>
        {% endif %}
    </div>
</div>

flaskshop/templates/orders/checkout_success.html
{% extends 'checkout/details.html' %}


{% block title %} Thank you {% endblock %}


{% block content %}
    <div class="row checkout__thankyoupage">
        <div class="col-xl-10 m-auto">
            <img class="checkout__thankyoupage__parrot lazyload lazypreload"
                 data-src="{{ url_for('static', filename='img/confirm-order-bg.png') }}"
                 srcset="{{ url_for('static', filename='img/confirm-order-bg.png') }} 1x, {{ url_for('static', filename='img/confirm-order-bg2x.png') }} %} 2x">
            <h1>
                Thank you for your <a href="{{ url_for('account.index') }}">order</a>!
            </h1>

            <p>
                We've sent a confirmation email with details to <span>{{ current_user.email }}</span>.<br>
                In case of any problems or questions please contact us.
            </p>
        </div>
        <div class="m-auto">
            <img class="checkout-pirate lazyload lazypreload" data-src="{{ url_for('static', filename='img/checkout-bg.png') }}"
                 srcset="">
            <p><a href="{{ url_for('public.home') }}" class="btn secondary">
                Continue shopping
            </a></p>
        </div>
    </div>
{% endblock %}

flaskshop/templates/orders/details.html
{% extends "base.html" %}


{% block title %}
Order {{ order }}
{% endblock %}

{% block breadcrumb %}
<ul class="breadcrumbs list-unstyled">
    <li>
        <a href="{{ url_for('public.home') }}">
            Home
        </a>
    </li>
    <li>
        <a href="{{ url_for('account.index') }}">
            Your account
        </a>
    </li>
    <li>
        <a href="{{ order.get_absolute_url() }}">
            Order {{ order }}
        </a>
    </li>
</ul>
{% endblock breadcrumb %}



{% block content %}

<div class="row order-details">
    <div class="col-lg-10 m-auto">
        <h2 class="order-details__header">
            Order: {{ order.token }}<br>
            Order Status: {{ order.status_human }}
        </h2>
        {% include "orders/_ordered_items_table.html" %}
        <div class="order-notes">
            {% if order.notes %}
            <h2 class="order-notes__header">Your note</h2>
            {% for note in order.notes %}
            <p>{{ note.content }}</p>
            {% endfor %}
            {% endif %}

        </div>
    </div>
</div>
{% endblock content %}