flaskshop/account/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user, login_user, logout_user
from pluggy import HookimplMarker

from .forms import AddressForm, LoginForm, RegisterForm, ChangePasswordForm
from .models import UserAddress, User
from flaskshop.utils import flash_errors
from flaskshop.order.models import Order

impl = HookimplMarker("flaskshop")


def index():
    form = ChangePasswordForm(request.form)
    orders = Order.get_current_user_orders()
    return render_template("account/details.html", form=form, orders=orders)


def login():
    """login page."""
    form = LoginForm(request.form)
    if form.validate_on_submit():
        login_user(form.user)
        redirect_url = request.args.get("next") or url_for("public.home")
        flash("You are log in.", "success")
        return redirect(redirect_url)
    else:
        flash_errors(form)
    return render_template("account/login.html", form=form)


@login_required
def logout():
    """Logout."""
    logout_user()
    flash("You are logged out.", "info")
    return redirect(url_for("public.home"))


def signup():
    """Register new user."""
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User.create(
            username=form.username.data,
            email=form.email.data.lower(),
            password=form.password.data,
            is_active=True,
        )
        login_user(user)
        flash("You are signed up.", "success")
        return redirect(url_for("public.home"))
    else:
        flash_errors(form)
    return render_template("account/signup.html", form=form)


def set_password():
    form = ChangePasswordForm(request.form)
    if form.validate_on_submit():
        current_user.update(password=form.password.data)
        flash("You have changed password.", "success")
    else:
        flash_errors(form)
    return redirect(url_for("account.index"))


def addresses():
    """List addresses."""
    addresses = current_user.addresses
    return render_template("account/addresses.html", addresses=addresses)


def edit_address():
    """Create and edit an address."""
    form = AddressForm(request.form)
    address_id = request.args.get("id", None, type=int)
    if address_id:
        user_address = UserAddress.get_by_id(address_id)
        form = AddressForm(request.form, obj=user_address)
    if request.method == "POST" and form.validate_on_submit():
        address_data = {
            "province": form.province.data,
            "city": form.city.data,
            "district": form.district.data,
            "address": form.address.data,
            "contact_name": form.contact_name.data,
            "contact_phone": form.contact_phone.data,
        }
        if address_id:
            UserAddress.update(user_address, **address_data)
            flash("Success edit address.", "success")
        else:
            UserAddress.create(**address_data)
            flash("Success add address.", "success")
        return redirect(url_for("account.index") + "#addresses")
    else:
        flash_errors(form)
    return render_template(
        "account/address_edit.html", form=form, address_id=address_id
    )


def delete_address(id):
    user_address = UserAddress.get_by_id(id)
    if user_address in current_user.addresses:
        UserAddress.delete(user_address)
    return redirect(url_for("account.index") + "#addresses")


@impl
def flaskshop_load_blueprints(app):
    bp = Blueprint("account", __name__)
    bp.add_url_rule("/", view_func=index)
    bp.add_url_rule("/login", view_func=login, methods=["GET", "POST"])
    bp.add_url_rule("/logout", view_func=logout)
    bp.add_url_rule("/signup", view_func=signup, methods=["GET", "POST"])
    bp.add_url_rule("/setpwd", view_func=set_password, methods=["POST"])
    bp.add_url_rule("/address", view_func=addresses)
    bp.add_url_rule("/address/edit", view_func=edit_address, methods=["GET", "POST"])
    bp.add_url_rule(
        "/address/<int:id>/delete", view_func=delete_address, methods=["POST"]
    )
    app.register_blueprint(bp, url_prefix="/account")

flaskshop/templates/_macros.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<div class="pagination">
  <ul class="pagination">
    <li {% if not pagination.has_prev %} class="disabled" {% endif %}>
      <a href="
          {% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
        &laquo;
      </a>
    </li>
    {% for p in pagination.iter_pages() %}
    {% if p %}
    {% if p == pagination.page %}
    <li class="active">
      <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
    </li>
    {% else %}
    <li>
      <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
    </li>
    {% endif %}
    {% else %}
    <li class="disabled"><a href="#">&hellip;</a></li>
    {% endif %}
    {% endfor %}
    <li {% if not pagination.has_next %} class="disabled" {% endif %}>
      <a href="
          {% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
        &raquo;
      </a>
    </li>
  </ul>
</div>
{% endmacro %}

{% macro menu(menu_items, horizontal=true) %}
<ul class="menu {% if horizontal %}nav mb-4 mb-md-0{% endif %}">
  {% for item in menu_items %}
  {% with children=item.children %}
  <li class="{% if horizontal %}nav-item{% endif %} {% if children %}nav-item__dropdown{% endif %} menu__item">
    <a class="{% if horizontal %}nav-link{% endif %}" href="{{ item.url }}">
      {{ item }}
    </a>
    {% if children %}
    <div class="{% if horizontal %}nav-item__dropdown-content{% else %}nav-item__submenu{% endif %}">
      <div class="container">
        <ul>
          {% for child in children %}
          <li>
            <a href="{{ child.url }}">
              {% if horizontal %}
              <strong>{{ child }}</strong>
              {% else %}
              {{ child }}
              {% endif %}
            </a>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
    {% endif %}
  </li>
  {% endwith %}
  {% endfor %}
</ul>
{% endmacro %}

{% macro format_address(address) %}
{{ address.province }}-{{ address.city }}-{{ address.district }}<br>
{{ address.address }}<br>
{{ address.contact_name }}<br>
{{ address.contact_phone }}<br>
{% endmacro %}

{% macro footer_menu(menu_items) %}
{% for item in menu_items %}
{% with children=item.children %}
<div class="col-6 col-md-2">
  <ul class="menu">
    <li class="{% if children %}nav-item__dropdown{% endif %} menu__item">
      <a href="{{ item.url }}">
        {{item.title}}
      </a>
      {% if children %}
      <hr />
      <div class="nav-item__submenu">
        <ul>
          {% for child in children %}
          <li>
            <a href="{{ child.url }}">
              {{child.title}}
            </a>
          </li>
          {% endfor %}
        </ul>
      </div>
      {% endif %}
    </li>
  </ul>
</div>
{% endwith %}
{% endfor %}
{% endmacro %}

{% macro navlink(endpoint, name, active='') %}
<li class="list-group-item {% if endpoint == request.endpoint or endpoint == active or active == True %}active{% endif %}">
    <a href="{{ url_for(endpoint) }}">{{ name }}</a>
</li>
{% endmacro %}

flaskshop/templates/base.html
{% import '_macros.html' as macros %}
<!DOCTYPE html>
<html class="no-js">

  <head>
    <title>{% block title %}flask store{% endblock %}</title>
    {% block meta %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="Saleor">
    <meta name="theme-color" content="#333333">
    <meta name="msapplication-TileColor" content="#2b5797">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="og:type" content="website">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    {% endblock meta %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='build/storefront.css') }}">
    {% block stylesheet %}{% endblock stylesheet %}

  </head>

  <body>
    {% block header %}
    <header class="navbar" role="navigation">
      <div class="navbar__login container-fluid">
        <div class=" d-none d-md-block container">
          <div class="row">
            <div class="col-6">
              <p class="text-left">{{ settings['project_title'].value }} - {{ settings['project_subtitle'].value }}</p>
            </div>
            <div class="col-6">
              <ul class="float-right">
                {% if current_user.is_authenticated %}
                {% if current_user.can_edit() %}

                <li>
                  <a href="{{ url_for('dashboard.index') }}" target="_blank" rel="noopener">
                    Dashboard
                  </a>
                </li>
                {% endif %}
                {{ run_hook("flaskbb_tpl_user_nav_loggedin_before") }}
                <li>
                  <a href="{{ url_for('account.index') }}">
                    Your Account</a>
                </li>

                <li>
                  <a href="{{ url_for('account.logout') }}">
                    Log Out</a>
                </li>

                {% else %}
                <li>
                  <a rel="nofollow" href="{{ url_for('account.signup') }}">
                    Register
                  </a>
                </li>
                <li>
                  <a rel="nofollow" href="{{ url_for('account.login') }}">
                    Log in
                  </a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar__brand container-fluid d-block">
        <div class="container">
          <div class="row no-gutters" style="width:100%">
            <div class="col-8 col-md-4 navbar__logo">
              <div class="menu-icon-mobile d-md-none navbar__brand__menu-toggle closed open">
                <svg data-src="{{ url_for('static', filename='img/mobile-menu.svg') }}" width="28px"
                  height="20px"></svg>
              </div>
              <a href="{{ url_for('public.home') }}">
                <svg data-src="{{ url_for('static', filename='img/logo-document.svg') }}" width="176px"
                  height="38px"></svg>
              </a>
            </div>
            <div class="col-2 col-md-5 navbar__search static">
              {% if current_app.config['USE_ES']  %}
              <div class="d-md-none mobile-search-icon">
                <svg data-src="{{ url_for('static', filename='img/search.svg') }}" width="30" height="30"></svg>
              </div>
              <form class="form-inline search-form" action="/search">
                <div class="mobile-close-search d-md-none">
                  <svg data-src="{{ url_for('static', filename='img/close.svg') }}" width="30" height="30"></svg>
                </div>
                <input class="form-control" type="text" name="q" value="{{request.args.get('q', '')}}"
                  placeholder="Search for product" required>
                <button class="btn btn-primary" type="submit" style="padding-top: 0px;padding-bottom: 0px">
                  Search<svg data-src="{{ url_for('static', filename='img/search.svg') }}" width="18" height="18"></svg>
                </button>
              </form>
              {% endif %}
            </div>
            <div class="col-2 col-md-3">
              <div class="navbar__brand__cart float-right">
                <a rel="nofollow" class="cart__icon" href="{{ url_for('checkout.cart_index') }}">
                  <span class="cart-label d-none d-md-inline-block">
                    Your Cart
                  </span>
                  <div class="navbar__brand__cart__icon">
                    <svg data-src="{{ url_for('static', filename='img/cart.svg') }}" width="24" height="24"></svg>
                  </div>
                  {% if current_user.is_authenticated and current_user_cart.quantity %}
                  <span class="badge ">
                    {{ current_user_cart.quantity }}
                  </span>
                  {% else %}
                  <span class="badge empty">
                    0
                  </span>
                  {% endif %}
                </a>
                <div class="cart-dropdown d-none">
                  {% include "public/cart_dropdown.html" %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% block navigation %}
      <div class="navbar__menu container d-block">
        <nav class="navigation">
          {{ macros.menu(top_menu) }}
        </nav>
      </div>
      {% endblock %}
    </header>
    {% endblock %}
    <div class="container maincontent">
      {% block topcontent %}{% endblock topcontent %}

      {% for message in get_flashed_messages(with_categories=True) %}
      <br>
      <div class="alert alert-{{ message[0] }}">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ message[1] }}
      </div>
      {% endfor %}

      {% block breadcrumb %}
      {% endblock breadcrumb %}
      {% block content %}
      {% endblock content %}
    </div>
    {% block footer %}
    <footer class="footer">
      <div class="footer__menus">
        <div class="container">
          <div class="row">
            {{ macros.footer_menu(bottom_menu) }}
            <div class="col-md-2 col-6">
              <ul class="menu">
                <li class="nav-item__dropdown menu__item">
                  <a>
                    <strong>
                      Account
                    </strong>
                  </a>
                  <hr />
                <li>
                  <a rel="nofollow" href="{{ url_for('checkout.cart_index') }}">
                    Your Cart
                  </a>
                </li>
                {% if current_user.is_authenticated %}
                {% if current_user.can_edit() %}
                <li>
                  <a href="{{ url_for('dashboard.index') }}" target="_blank" rel="noopener">
                    Dashboard
                  </a>
                </li>
                {% endif %}
                <li>
                  <a href="{{ url_for('account.index') }}">
                    Your account
                  </a>
                </li>

                <li>
                  <a href="{{ url_for('account.logout') }}">
                    Log out</a>
                </li>

                {% else %}
                <li>
                  <a rel="nofollow" href="{{ url_for('account.signup') }}">
                    Register
                  </a>
                </li>
                <li>
                  <a rel="nofollow" href="{{ url_for('account.login') }}">
                    Log in
                  </a>
                </li>
                {% endif %}
              </ul>
            </div>
            <div class="offset-md-2 col-md-4 col-12">
              <div class="footer__menus__social-container">
                <div class="footer__menus__social">
                  <a target="_blank" rel="noopener" class="social-footer" href="https://www.facebook.com/mirumeelabs/">
                    <svg data-src="{{ url_for('static', filename='img/facebook-logo.svg') }}" width="45px"
                      height="45px" />
                  </a>
                  <a target="_blank" rel="noopener" class="social-footer" href="https://github.com/mirumee/saleor">
                    <svg data-src="{{ url_for('static', filename='img/github-logo.svg') }}" width="45px"
                      height="45px" />
                  </a>
                  <a target="_blank" rel="noopener" class="social-footer" href="https://twitter.com/getsaleor">
                    <svg data-src="{{ url_for('static', filename='img/twitter-logo.svg') }}" width="45px"
                      height="45px" />
                  </a>
                  <a target="_blank" rel="noopener" class="social-footer" href="https://plus.google.com/+Mirumee">
                    <svg data-src="{{ url_for('static', filename='img/google-logo.svg') }}" width="45px"
                      height="45px" />
                  </a>
                  <a target="_blank" rel="noopener" class="social-footer" href="https://www.meetup.com/Mirumee-Talks/">
                    <svg data-src="{{ url_for('static', filename='img/meetup-logo.svg') }}" width="45px"
                      height="45px" />
                  </a>
                  <a target="_blank" rel="noopener" class="social-footer"
                    href="https://linkedin.com/company/mirumee-software">
                    <svg data-src="{{ url_for('static', filename='img/linkedin-logo.svg') }}" width="45px"
                      height="45px" />
                  </a>
                  <a target="_blank" rel="noopener" class="social-footer" href="https://dribbble.com/mirumee">
                    <svg data-src="{{ url_for('static', filename='img/dribbble-logo.svg') }}" width="45px"
                      height="45px" />
                  </a>
                  <a target="_blank" rel="noopener" class="social-footer"
                    href="https://www.instagram.com/explore/tags/mirumee/">
                    <svg data-src="{{ url_for('static', filename='img/instagram-logo.svg') }}" width="45px"
                      height="45px" />
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="footer__copy">
        <div class="container">
          <div class="row">
            <div class="col-4">
              <a href="{{ url_for('public.home') }}" class="footer__logo float-md-left">
                <svg data-src="{{ url_for('static', filename='img/logo-document.svg') }}" width='176px' height='38px' />
              </a>
            </div>
            <div class="col-8 footer__copy-text">{{ settings['project_copyright'].value }}</div>
          </div>
        </div>
      </div>
    </footer>
    {% endblock %}
    {% block footer_scripts %}
      <script src="{{ url_for('static', filename='build/storefront.js') }}"></script>
    {% endblock footer_scripts %}
  </body>

</html>

flaskshop/templates/no_nav_base.html
{% extends "base.html" %}

{% block navigation %}

{% endblock %}